{
 "title": "FireFighter",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "FireRating",
   "type": "stat",
   "description": "display a rating of the fire probability",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lucas.gosteli's Bucket\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Measure/fireRating\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "C°" } },
   "targets": [
    {
     "query": "from(bucket: \"lucas.gosteli's Bucket\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Measure/temperature\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "query": "from(bucket: \"lucas.gosteli's Bucket\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Measure/humidity\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")"
    }
   ]
  },
  {
   "title": "Pression",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "query": "from(bucket: \"lucas.gosteli's Bucket\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Measure/pressure\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")"
    }
   ]
  }
 ]
}